# The URL the site will be built for
base_url = "https://leotsarev.ru"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "hyde"

title = "Леонид Царев"
description = ""

[extra]
hyde_links = [
    {url = "/develop", name = "Программирование"},
    {url = "/develop/articles/", name = " - Статьи"},
    {url = "/larp", name = "Ролевое"},
    {url = "/larp/games", name = " - Игры"},
    {url = "/personal", name = "Личное"},
    {url = "/personal/wishlist", name = " - Вишлист"},
    {url = "/personal/korvet", name = " - Корвет"},
    {url = "/personal/grandfather", name = " - Дед"},
    {url = "/archive", name = "Архив"},
]

hyde_theme = "theme-base-08"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true