name: Mirror to gitverse

on: [push]


jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: mirror-repository
      uses: spyoungtech/mirror-action@v0.7.0
      with:
        REMOTE: ssh://git@gitverse.ru:2222/leotsarev/leotsarev.ru.git
        GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_KEY }}
        GIT_SSH_KNOWN_HOSTS: ${{ vars.GIT_SSH_KNOWN_HOSTS }
        DEBUG: "true"
